// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gaming-app/NeonCommand.tsx": () => import("../components/mockups/gaming-app/NeonCommand.tsx"),
  "./components/mockups/gaming-app/RetroArcade.tsx": () => import("../components/mockups/gaming-app/RetroArcade.tsx"),
  "./components/mockups/gaming-app/SleekStudio.tsx": () => import("../components/mockups/gaming-app/SleekStudio.tsx")
};
